export default {
  ENCRYPT_STRING: 'ENCRYPT_STRING',
  DECRYPT_STRING: 'DECRYPT_STRING',
  SAVE_TO_STORE: 'SAVE_TO_STORE',
  GET_FROM_STORE: 'GET_FROM_STORE',

  TINKOFF_CREATE_SDK: 'TINKOFF_CREATE_SDK',
}