export const ipcEvents = {
  ENCRYPT_STRING: 'ENCRYPT_STRING',
  DECRYPT_STRING: 'DECRYPT_STRING',
  SAVE_TO_STORE: 'SAVE_TO_STORE',
  GET_FROM_STORE: 'GET_FROM_STORE',

  TINKOFF_CREATE_SDK: 'TINKOFF_CREATE_SDK',
  TINKOFF_GET_ACCOUNTS: 'TINKOFF_GET_ACCOUNTS',

  START_TRADING: 'START_TRADING',
  PAUSE_TRADING: 'PAUSE_TRADING',
  strategylog: 'strategylog'
};