export const ipcEvents = {
  ENCRYPT_STRING: 'ENCRYPT_STRING',
  DECRYPT_STRING: 'DECRYPT_STRING',
  SAVE_TO_STORE: 'SAVE_TO_STORE',
  GET_FROM_STORE: 'GET_FROM_STORE',

  TINKOFF_CREATE_SDK: 'TINKOFF_CREATE_SDK',
  TINKOFF_GET_ACCOUNTS: 'TINKOFF_GET_ACCOUNTS',
  TINKOFF_SUBSCRIBE_ON_CANDLES: 'TINKOFF_SUBSCRIBE_ON_CANDLES',
  TINKOFF_GET_CANDLES_STREAM: 'TINKOFF_GET_CANDLES_STREAM',
  TINKOFF_ON_CANDLES_STREAM: 'TINKOFF_ON_CANDLES_STREAM',
  TINKOFF_GET_POSITIONS: 'TINKOFF_GET_POSITIONS',


  START_TRADING: 'START_TRADING',
  PAUSE_TRADING: 'PAUSE_TRADING',
  RESUME_TRADING: 'RESUME_TRADING',

  GET_INSTRUMENTS: 'GET_INSTRUMENTS',

  CHANGE_STRATEGY_CONFIG: 'CHANGE_STRATEGY_CONFIG',
  LOAD_STRATEGY_CONFIG: 'LOAD_STRATEGY_CONFIG',
  STRATEGY_LOG: 'STRATEGY_LOG',
};
